name: Dependency Snapshot

on:
  push:
    branches:
      - master

jobs:
  dependency-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
           distribution: 'temurin' # or adopt, zulu, etc.
           java-version: '11'

      - name: Build with Maven
        run: mvn clean 

      - name: Submit dependency snapshot
        uses: advanced-security/maven-dependency-tree-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build and Push Docker Images
        uses: ravisree900/docker-build-push@v4
        with: 
          image: ravisree900/java_app@maven
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
